### ISSUE TITLE
Tensorflow 2.2.0rc1 Non AVX

### ISSUE THREAD

**Issue by rodvieirasilva** [hamling-ling/mlenv#15]
Please, could you provide the file tensorflow-2.2.0rc1-cp36-cp36m-linux_x86_64.whl from Dockerfile_NonAVX_Tf2.

It's so hard to find the whl files compiled.

Thank you very much.

**Comment by hamling-ling** [comment]
Wow! Visitor to my repo!
I put whl in my google drive public folder. You can download from following link

https://drive.google.com/open?id=1x8BPodo87vdlgqom1ve4ynsFJcYUSnFI

Note that I used "-march Nehalem" in configure option so I'm not sure if it works in your environment.

How I build is here
https://github.com/hamling-ling/mlenv/blob/master/tensorflow/tf_devel.sh

**Comment by rodvieirasilva** [comment]
Thank you very much. 
Star to your project. :)
